<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Commit;
/**
 * CommitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitRepository extends \Doctrine\ORM\EntityRepository
{}