<?php

namespace AppBundle\Repository;

/**
 * FileActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileActionRepository extends \Doctrine\ORM\EntityRepository
{
}
