<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Payload;

/**
 * PayloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayloadRepository extends \Doctrine\ORM\EntityRepository
{}
