<?php

namespace AppBundle\Manager;

use AppBundle\Entity\File;
use Doctrine\ORM\EntityManagerInterface;

/**
 * UserManager
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileManager
{
    private $em;
    private $fileRepository;

    public function __construct( EntityManagerInterface $em )
    {
        $this->em = $em;
        $this->fileRepository = $this->em->getRepository('AppBundle:File');
    }

    public function getFileFromPayload( $filePath )
    {
        if( null === $file = $this->fileRepository->findOneByPath($filePath)) {

            $file = new File();

            $file->setPath($filePath);

            $this->em->persist($file);
            $this->em->flush();
        }
        return $file;
    }

}
